// flow-typed signature: 41586d969b980cd9ae5b4ca5d271d1f6
// flow-typed version: <<STUB>>/mocha-lcov-reporter_v1.2.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-lcov-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-lcov-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mocha-lcov-reporter/lib/index' {
  declare module.exports: any;
}

declare module 'mocha-lcov-reporter/lib/lcov' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mocha-lcov-reporter/index' {
  declare module.exports: $Exports<'mocha-lcov-reporter'>;
}
declare module 'mocha-lcov-reporter/index.js' {
  declare module.exports: $Exports<'mocha-lcov-reporter'>;
}
declare module 'mocha-lcov-reporter/lib/index.js' {
  declare module.exports: $Exports<'mocha-lcov-reporter/lib/index'>;
}
declare module 'mocha-lcov-reporter/lib/lcov.js' {
  declare module.exports: $Exports<'mocha-lcov-reporter/lib/lcov'>;
}
