name: 'Unit Tests'

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - master

jobs:
  unit:
    name: 'Unit Tests'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node: [14, 16]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm run build && npm t
